---
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
    stylelint:
        config: 'stylelint.config.js'
        fixer: true

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'

fixers:
    enable: true